wandb_project: wmt21-qe # optional
do_train: True
output_dir: results/qe_da/testing
adapter_path: path/to/trained/adapter
max_seq_len: 50
task: qe_da   # qe_da = task 1, qe_hter = task 2
report_to: none
madx2: False
#prompt: [original, translation]
train:
  train_batchsize: 16
  eval_batchsize: 32
  max_steps: 1000
  logging_steps: 10
  eval_steps: 250
  gradient_accumulation_steps: 1
  save_total_limit: 2
  amp: True
  epochs: 1
  pair: [en, de]
test:
  batchsize: 32
  pairs:
    - [en, de]
    - [en, zh]
    - [et, en]
#    - [ne, en] #missing
#   - [ro, en]
#   - [ru, en]
#   - [si, en]